spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mymo
    driver-class-name: org.postgresql.Driver
    username: mymo
    password: mymo

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
